/**
 * AUTO-GENERATED by scripts/03_merge_and_export.py
 * Do not edit manually — run the pipeline scripts to regenerate.
 */
import type { TestData } from '../types';
import { cambridge1Test1 } from './generated/tests/book1_test1';
import { cambridge1Test2 } from './generated/tests/book1_test2';
import { cambridge1Test3 } from './generated/tests/book1_test3';
import { cambridge1Test4 } from './generated/tests/book1_test4';
import { cambridge15Test1 } from './generated/tests/book15_test1';
import { cambridge15Test2 } from './generated/tests/book15_test2';
import { cambridge15Test3 } from './generated/tests/book15_test3';
import { cambridge15Test4 } from './generated/tests/book15_test4';

export const generatedTestsRepository: Record<string, TestData> = {
  '1-1': cambridge1Test1,
  '1-2': cambridge1Test2,
  '1-3': cambridge1Test3,
  '1-4': cambridge1Test4,
  '15-1': cambridge15Test1,
  '15-2': cambridge15Test2,
  '15-3': cambridge15Test3,
  '15-4': cambridge15Test4
};

export const availableTests = [
  {
    "book": 1,
    "test": 1,
    "listeningQs": 15,
    "readingQs": 22
  },
  {
    "book": 1,
    "test": 2,
    "listeningQs": 21,
    "readingQs": 23
  },
  {
    "book": 1,
    "test": 3,
    "listeningQs": 22,
    "readingQs": 28
  },
  {
    "book": 1,
    "test": 4,
    "listeningQs": 30,
    "readingQs": 23
  },
  {
    "book": 15,
    "test": 1,
    "listeningQs": 36,
    "readingQs": 22
  },
  {
    "book": 15,
    "test": 2,
    "listeningQs": 34,
    "readingQs": 18
  },
  {
    "book": 15,
    "test": 3,
    "listeningQs": 21,
    "readingQs": 28
  },
  {
    "book": 15,
    "test": 4,
    "listeningQs": 20,
    "readingQs": 25
  }
];
